sudo: required
dist: trusty
language: node_js
node_js:
  - "10"
cache:
  yarn: true
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
deploy:
  provider: pages
  script: yarn build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: test-pages
  local-dir: assets/dist
  on:
    branch: vuex
