language: node_js
node_js:
  - 0.10

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem update --system
  - gem install sass
  - npm install --quiet -g karma
  - npm install --quiet -g protractor
  - npm install --quiet -g grunt-cli
  - npm install --quiet -g bower
  - bower install
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script:
  - webdriver-manager update
  - grunt test