language: node_js
node_js:
  - 11
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn run test:unit
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  fqdn: www.betterthanpredator.com
  on:
    branch: master
