language: node_js
node_js:
  - 16
cache:
  directories:
    - node_modules
script:
  - yarn run lint
  - yarn run test
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  fqdn: www.betterthanpredator.com
  on:
    branch: master
