language: node_js
node_js:
  - 11
script:
  - npm run lint
  - npm run test:unit
  - npm run test:e2e
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: 'dist'
  on:
    branch: master
