language: node_js
node_js:
  - 11
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test:unit
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: 'dist'
  on:
    branch: master
